### ISSUE TITLE
Tags field in authentication

### ISSUE THREAD

**Issue by vicariousdrama** [relaytools/cookiecutter#2]
Shouldn't the value of the tags field be an empty array ? Or does the call to sign correct for this?

https://github.com/relaytools/cookiecutter/blob/8d68c7ec0d9ef96a0d691ea81d033b1ca28bb7be/cmd/util.go#L69

![image](https://github.com/user-attachments/assets/7c060ac4-8c16-4546-b544-421bc3b59f8e)

**Comment by jeremyd** [comment]
the API endpoint fills in tags empty array for you .. so nil must be equivalent here for  == []  because otherwise the sigs wouldn't match.
